version: '3'
services:

  #PHP Service
  php:
    image: php:7.4-fpm-alpine
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
      - wordpress_data:/var/www/html
      - wpsocket:/var/run/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_HOST: "%"
    env_file:
      - env/mysql.env 
    volumes:
      - dbdata:/var/lib/mysql/
      - ./logs/mysql:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql-files
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: http://localhost/pma/
    restart: always
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.2-fpm-alpine
    volumes:
      - wordpress_data:/var/www/html
      - ./php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - wpsocket:/var/run/
    restart: always
    env_file:
      - env/wordpress.env
    networks:
      - app-network

  #Docker Networks
networks:
  app-network:
    driver: bridge
  #Volumes
volumes:
    dbdata:
    wpsocket:
    wordpress_data: 
